### PR TITLE
Add aeson instances

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by sjakobi** [comment]
Looks like travis hasn't been enabled for this repo yet. Could you please do this, @chrisdone?

**Comment by sjakobi** [comment]
Also, if you would prefer to keep all the aeson instances in one module, I'd propose moving `Abs`, `Dir` etc. and the parsing functions to `Path.Internal`.

**Comment by chrisdone** [comment]
Enabled. Closing and opening the PR should trigger a travis build.

**Comment by chrisdone** [comment]
The PR looks great from here!

**Comment by chrisdone** [comment]
The build failures look a bit useless. I'm going to update the travis file.

**Comment by sjakobi** [comment]
The error message with `aeson-0.8.0.2` [here](https://travis-ci.org/chrisdone/path/jobs/138026757) and [there](https://travis-ci.org/chrisdone/path/jobs/138026758) is

```
  1) Aeson Instances Decoding "/foo/bar" as a Path Abs Dir should succeed.
       expected: Right "/foo/bar/"
        but got: Left "Failed reading: satisfy"
```

I've found some hints in https://github.com/bos/aeson/issues/113 and will come back to this.

**Comment by chrisdone** [comment]
I'll come back to this later today.

**Pull request merged**
