### PR TITLE
Improve description of the package

### PR DESCRIPTION
**Pull request by mrkkrp**
See comment of the second commit.

### CODE REVIEW

**Comment by mrkkrp** [comment]
Can you enable issues for this repo?

**Comment by chrisdone** [comment]
Nice work, cheers!

**Comment by mrkkrp** [comment]
Oh, I just have a snippet for these things and `experimental` is most commonly used option for new packages and I left it as is.

**Comment by mrkkrp** [comment]
I would like to ask you again to enable issues for this repo. Since I cannot open an issue, I will point out right here that this:

```
λ> parseRelFile "."
"."
```

Is probably wrong, this should not succeed. On Unix-like systems you cannot have a file named `"."`, because this name is already assigned to current directory, thus this cannot be valid relative file name.

**Comment by mrkkrp** [comment]
@chrisdone, Also, why not to use `isValid` checks provided by `filepath` when parsing paths?

**Comment by chrisdone** [comment]
@mrkkrp Good catch, `parseRelFile` should reject `"."`. I'm going to fix that. I've enabled issues on the repo.

I'll check out `isValid` to see what it gets us.

**Comment by chrisdone** [comment]
@mrkkrp It seems that `isValid` buys us some checks. I've included use of it as `0.5.5`. Thanks for the suggestion!

**Pull request merged**
